/**
 * API contract types shared between the FastAPI backend and the Next.js web app.
 * Backend serializes into these shapes; the frontend never recomputes them.
 */

export * from "./constants";

/** Chat request body for `POST /api/query`. */
export interface QueryRequest {
  /** User question text. */
  query: string;
  /** Project registry key the question is scoped to (regex `^[a-z0-9_]{2,40}$`). */
  project_key: string;
  /** Chat session id (UUID) generated by the client. */
  session_id?: string;
  /** Anonymous persistent device id (UUID v4) generated once by the client (D7). */
  device_id?: string;
  /** ISO 8601 effective date used to filter documents by `effective_date`. */
  as_of?: string;
  /** Recent conversation turns (client keeps at most 4 rounds). */
  history?: QueryHistoryItem[];
}

/** Request body for `POST /api/lead` — customer phone capture (Story 6.4 + G1). */
export interface LeadSubmitRequest {
  /** Project registry key the lead belongs to (required — BE populates from request, G1). */
  project_key: string;
  /** Chat session id (UUID) generated by the client. */
  session_id?: string;
  /** Anonymous persistent device id (UUID v4) sent alongside the lead (D7). */
  device_id?: string;
  /** Customer display name. */
  name?: string;
  /** Customer phone (Vietnamese format). */
  phone: string;
  /** Consent to be called back by a sales specialist. */
  consent: boolean;
  /** Free-text note about the lead. */
  note?: string;
  /** Indicative budget in VND. */
  budget_vnd?: number;
}

export type QueryHistoryRole = "user" | "assistant";

export interface QueryHistoryItem {
  role: QueryHistoryRole;
  content: string;
}

/** Document source cited in an answer. */
export interface Source {
  doc_id: string;
  title: string;
  section?: string;
  effective_from?: string;
  kind: string;
}

/** Legal fact extracted from sources, with evidence. */
export interface FactEvidence {
  fe_id: string;
  subject: string;
  policy_key?: string;
  fields: Record<string, number | string | null>;
  note?: string;
}

/** Qualifier explaining why an image appears in the gallery, set by the backend. */
export type ImageMatch = "exact" | "similar" | "semantic";

/** Illustrative asset attached to an answer (floor plan, price sheet, flyer, payment). */
export interface Image {
  image_id: string;
  kind: string;
  title: string;
  caption: string | null;
  alt_text: string | null;
  url_cdn: string;
  width: number | null;
  height: number | null;
  score: number;
  /** Why this image was retrieved. "exact" = the exact unit asked; "similar" = a comparable one; "semantic" = loose relevance. */
  match?: ImageMatch;
  /** Vietnamese sentence shown with the match badge; null/absent when match is semantic. */
  reason?: string | null;
}

/** Motion format of a project film attached to the greeting/welcome. */
export type VideoKind = "brand" | "drone";

/**
 * Project film shown in the welcome (brand film / drone tour). The MP4 lives on
 * the CDN while `poster_url` is a render used as the loading/fallback frame.
 * Duration/dimensions are optional: the player must never depend on them.
 */
export interface Video {
  title: string;
  url_cdn: string;
  kind?: VideoKind;
  poster_url?: string | null;
  width?: number | null;
  height?: number | null;
  duration?: number | null;
}

/** Nearby amenity/landmark from the maps leg (Google Places or static fallback). */
export interface NearbyPlace {
  name: string;
  kinds: string[];
  lat: number;
  lng: number;
  distance_m?: number;
  address?: string;
  rating?: number;
}

export type Confidence = "HIGH" | "MEDIUM" | "LOW";

export type StructuredPath = "spec" | "nl2sql" | "affordability" | "none";

export interface QueryResponseRouting {
  needs_rag: boolean;
  needs_sql: boolean;
  structured_path: StructuredPath;
}

/** Non-streaming response of `POST /api/query`. */
export interface QueryResponse {
  answer: string;
  sources: Source[];
  facts: FactEvidence[];
  places: NearbyPlace[];
  images?: Image[];
  confidence: Confidence;
  requires_review: boolean;
  routing: QueryResponseRouting;
  trace_id: string;
  latency_ms: number;
}

/** Payload of the SSE `routing` event (Story 4.5) — intent/panel + optional CTA hint. */
export interface SseRoutingPayload {
  intent: string;
  conv_state: string;
  panel_hint: "map" | "company" | "affordability" | "lead" | "none";
  lead_cta_hint: string | null;
}

export type SseEventName =
  | "ack"
  | "routing"
  | "places"
  | "sources"
  | "facts"
  | "images"
  | "videos"
  | "token"
  | "done"
  | "error";

/** Non-streaming response of `POST /api/llms-hello` (first-open greeting). */
export interface HelloResponse {
  greeting: string;
  trace_id: string;
  images?: Image[];
  videos?: Video[];
}

/** A single event in the SSE stream of `POST /api/query`. */
export interface SseEvent {
  event: SseEventName;
  data: unknown;
}

/* ------------------------------------------------------------------ */
/* VND currency formatting — single source of truth for money display. */
/* ------------------------------------------------------------------ */

const vndFormatter = new Intl.NumberFormat("vi-VN", {
  maximumFractionDigits: 0,
});

/**
 * Format a number as a VND string using the vi-VN locale.
 * Example: 1_500_000_000 -> "1.500.000.000đ".
 */
export function formatVND(value: number): string {
  return `${vndFormatter.format(value)}đ`;
}
